name: Build Kernel GKI with Clang-r547379

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEFCONFIG: gs201_defconfig
      ZIPNAME: Kernel-A13-GoPix-7-Series-KSu-next.zip
      KBUILD_BUILD_USER: "@riyanjulai"
      KBUILD_BUILD_HOST: "Ubuntu-Linux"

    steps:
    - name: Checkout Kernel
      uses: actions/checkout@v3
      with:
        repository: RONNIE158/android_kernel_google_gs201
        ref: 13.0.0-sultan
        path: kernel

    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y bc bison build-essential flex lld \
         libssl-dev libncurses5-dev libncursesw5-dev \
         python3 python3-pip rsync zip \
         binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
         gcc-aarch64-linux-gnu gcc g++ git curl wget unzip \
         libelf-dev dwarves device-tree-compiler clang llvm lz4 xz-utils zstd


    - name: Download Clang-r547379
      run: |
        mkdir -p ${{ github.workspace }}/clang-r547379
        wget -P ${{ github.workspace }}/clang-r547379/ https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz
        tar -xf ${{ github.workspace }}/clang-r547379/clang-r547379.tar.gz -C ${{ github.workspace }}/clang-r547379/
        rm -f ${{ github.workspace }}/clang-r547379/clang-r547379.tar.gz
        echo "${{ github.workspace }}/clang-r547379/bin" >> $GITHUB_PATH

    - name: Set up AnyKernel
      run: |
        if [ ! -d ${{ github.workspace }}/anykernel ]; then
          git clone https://github.com/sudoyottaxbyte/any_kernel.git ${{ github.workspace }}/anykernel
        fi

    - name: Build Kernel
      run: |
        cd kernel
        mkdir -p out
        make O=out ARCH=arm64 ${{ env.DEFCONFIG }}
          sed -i 's/CONFIG_LTO_CLANG_FULL=y/# CONFIG_LTO_CLANG_FULL is not set/' out/.config
          sed -i 's/# CONFIG_LTO_CLANG_THIN is not set/CONFIG_LTO_CLANG_THIN=y/' out/.config
        make -j$(nproc) O=out ARCH=arm64 \
        CC=clang LD=ld.lld AR=llvm-ar AS=llvm-as NM=llvm-nm \
        OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip \
        CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
        LLVM=1 LLVM_IAS=1 LTO=thin CHECKSYSCALLS=n | tee build.log



    - name: Prepare AnyKernel
      run: |
        cp kernel/out/arch/arm64/boot/Image.lz4 anykernel/
        cp kernel/out/arch/arm64/boot/dts/google/dtbo.img anykernel/

    - name: Zip Kernel
      run: |
        cd anykernel
        zip -r9 $ZIPNAME *
        mv $ZIPNAME ${{ github.workspace }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel-zip
        path: ${{ github.workspace }}/$ZIPNAME
