name: Build Kernel from Kernel Tree

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEFCONFIG: gs201_defconfig  # ganti sesuai defconfig device kamu
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget unzip zip curl bc bison build-essential flex lld \
          libssl-dev libncurses5-dev libncursesw5-dev \
          python3 python3-pip rsync ccache zip \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
          libelf-dev dwarves \
          coreutils device-tree-compiler \
          clang llvm \
          lz4 xz-utils zstd \
          android-sdk-libsparse-utils \
          libncurses-dev \
          gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
     

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Build Kernel
        run: ./build.sh
