name: Build Kernel GKI with Clang-r547379

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEFCONFIG: gs201_defconfig
      ZIPNAME: Kernel-A13-GoPix-7-Series-KSu-next.zip
      KBUILD_BUILD_USER: "@riyanjulai"
      KBUILD_BUILD_HOST: "Ubuntu-Linux"
      PATCH_REPO: Linux-on-droid/lindroid-drm-loopback

    steps:
    - name: Checkout Kernel
      uses: actions/checkout@v3
      with:
        repository: RONNIE158/android_kernel_google_gs201
        ref: 13.0.0-sultan
        path: kernel

    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y bc bison build-essential flex lld \
         libssl-dev libncurses5-dev libncursesw5-dev \
         python3 python3-pip rsync zip \
         binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
         gcc-aarch64-linux-gnu gcc g++ git curl wget unzip \
         libelf-dev dwarves device-tree-compiler clang llvm lz4 xz-utils zstd     
    
    - name: Download Clang-r547379
      run: |
        mkdir -p ${{ github.workspace }}/clang-r547379
        wget -P ${{ github.workspace }}/clang-r547379/ https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz
        tar -xf ${{ github.workspace }}/clang-r547379/clang-r547379.tar.gz -C ${{ github.workspace }}/clang-r547379/
        rm -f ${{ github.workspace }}/clang-r547379/clang-r547379.tar.gz
        echo "${{ github.workspace }}/clang-r547379/bin" >> $GITHUB_PATH

    - name: Set up AnyKernel
      run: |
        if [ ! -d ${{ github.workspace }}/anykernel ]; then
          git clone https://github.com/sudoyottaxbyte/any_kernel.git ${{ github.workspace }}/anykernel
        fi
   
    - name: Checkout Lindroid DRM Patch
      uses: actions/checkout@v3
      with:
        repository: ${{ env.PATCH_REPO }}
        path: drm-dkms

    - name: Apply Lindroid DRM Patch
      run: |
        cd kernel
        echo 'obj-y += lindroid-drm/' >> drivers/Makefile
        echo 'source "drivers/lindroid-drm/Kconfig"' >> drivers/Kconfig

        # Copy source lindroid-drm ke tree kernel
        cp -r ../drm-dkms drivers/lindroid-drm    

    - name: Build Kernel
      run: |
        cd kernel
        mkdir -p out
        make O=out ARCH=arm64 ${{ env.DEFCONFIG }}
        make -j$(nproc) O=out ARCH=arm64 \
          CC=clang LD=ld.lld AR=llvm-ar AS=llvm-as NM=llvm-nm \
          OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip \
          CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
          LLVM=1 LLVM_IAS=1 LTO=none CHECKSYSCALLS=n modules | tee build.log

    - name: Verify Lindroid DRM Build
      run: |
        cd kernel
        if grep -q "AR      drivers/lindroid-drm/built-in.a" build.log; then
          echo "✅ Lindroid DRM built successfully"
        else
          echo "❌ Lindroid DRM NOT built"
          exit 1
        fi    

    - name: Prepare AnyKernel
      run: |
        cp kernel/out/arch/arm64/boot/Image.lz4 anykernel/
        cp kernel/out/arch/arm64/boot/dts/google/dtbo.img anykernel/

    - name: Zip Kernel
      run: |
        cd anykernel
        zip -r9 $ZIPNAME *
        mv $ZIPNAME ${{ github.workspace }}

    - name: Upload Kernel ZIP
      uses: actions/upload-artifact@v4
      with:
        name: kernel-zip
        path: /home/runner/work/android_kernel_google_gs201/android_kernel_google_gs201/Kernel-A13-GoPix-7-Series-KSu-next.zip
